<a href="https://colab.research.google.com/github/EshwarDhande/Model-Tweaks/blob/main/Quickplay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [1]:

!pip install transformers

from transformers import AutoModel, AutoTokenizer

model_name = 'bert-base-uncased'

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [3]:
print(model)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [4]:
seventh_layer = model.encoder.layer[6]

In [5]:
attention_weights = seventh_layer.attention.self.query.weight
attention_biases = seventh_layer.attention.self.query.bias

print("Original attention weights shape:", attention_weights.shape)
print("Original attention biases shape:", attention_biases.shape)


Original attention weights shape: torch.Size([768, 768])
Original attention biases shape: torch.Size([768])


In [6]:
print("Original attention weights :", attention_weights)
print("Original attention biases :", attention_biases)

Original attention weights : Parameter containing:
tensor([[-0.0253,  0.0489, -0.0148,  ...,  0.0431, -0.0253,  0.0013],
        [-0.0143, -0.0465, -0.0020,  ..., -0.0073, -0.0296,  0.0208],
        [ 0.0147, -0.0400, -0.0344,  ..., -0.0697, -0.1240, -0.0031],
        ...,
        [-0.0214, -0.0160, -0.0680,  ...,  0.0233, -0.0359,  0.0355],
        [-0.0297,  0.0270,  0.0464,  ...,  0.0691,  0.0293,  0.0095],
        [-0.0012, -0.0403,  0.0343,  ..., -0.0742,  0.0371,  0.0421]],
       requires_grad=True)
Original attention biases : Parameter containing:
tensor([-1.7320e-01,  2.7564e-01,  1.6801e-01, -1.0946e-01,  1.6433e-01,
        -1.1501e-01, -2.5965e-01, -1.3676e-01, -3.0756e-01, -4.5222e-01,
         1.0455e-01, -8.2313e-02, -9.7356e-02, -2.0522e-02,  1.1782e-01,
         7.8542e-02, -1.1049e-01,  8.0185e-02,  3.4537e-02, -6.8996e-02,
        -6.8539e-04,  2.3121e-01,  1.2190e-01,  1.4254e-01, -7.6825e-02,
         1.5386e-01,  9.6756e-04,  1.0246e-01,  1.4043e-01, -1.5966e-01,


In [10]:
random_weights = torch.randn_like(attention_weights)
random_biases = torch.randn_like(attention_biases)


In [11]:
seventh_layer.attention.self.query.weight.data = random_weights
seventh_layer.attention.self.query.bias.data = random_biases

In [12]:
print("Modified attention weights:", seventh_layer.attention.self.query.weight)
print("Modified attention biases:", seventh_layer.attention.self.query.bias)

Modified attention weights: Parameter containing:
tensor([[ 1.1232, -2.0663, -0.3869,  ..., -0.9638,  1.0049, -0.1363],
        [ 0.3644, -0.4459,  0.3675,  ...,  0.5589,  0.2482,  0.7973],
        [ 0.5483,  1.7345, -0.1110,  ...,  0.7413, -0.2864,  0.5573],
        ...,
        [ 0.3874, -0.3777, -0.8853,  ...,  0.4760,  0.3183, -0.2340],
        [ 0.9746,  0.0902, -1.0719,  ..., -0.6945, -1.2466, -0.3071],
        [ 1.2965,  0.9028,  0.9281,  ..., -1.9690, -1.2167,  2.0736]],
       requires_grad=True)
Modified attention biases: Parameter containing:
tensor([-8.6173e-01, -7.4179e-01,  5.5969e-01, -3.4505e-01,  9.2275e-01,
        -9.2913e-01, -4.6782e-01,  3.9303e-01,  3.7233e-02,  9.5958e-01,
         1.7285e+00, -7.3191e-01,  5.0729e-01, -2.2224e+00,  5.2406e-01,
         5.7105e-01, -9.3041e-01, -1.1125e+00,  3.6708e-01, -3.5432e-01,
        -8.9508e-01, -5.0415e-02,  1.5396e+00, -8.0105e-01, -1.0225e+00,
        -1.5803e+00, -1.4517e+00, -8.0480e-01, -1.4903e+00, -3.7841e-01,
  

In [13]:
model_name = 'gpt2'

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

In [14]:
print(model)

GPT2Model(
  (wte): Embedding(50257, 768)
  (wpe): Embedding(1024, 768)
  (drop): Dropout(p=0.1, inplace=False)
  (h): ModuleList(
    (0-11): 12 x GPT2Block(
      (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (attn): GPT2Attention(
        (c_attn): Conv1D()
        (c_proj): Conv1D()
        (attn_dropout): Dropout(p=0.1, inplace=False)
        (resid_dropout): Dropout(p=0.1, inplace=False)
      )
      (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (mlp): GPT2MLP(
        (c_fc): Conv1D()
        (c_proj): Conv1D()
        (act): NewGELUActivation()
        (dropout): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
)


In [17]:
layer_index = 6
seventh_layer = model.transformer.h[layer_index]

AttributeError: 'GPT2Model' object has no attribute 'transformer'

In [4]:
from transformers import GPT2Tokenizer, GPT2Model

model_name = 'gpt2'

tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2Model.from_pretrained(model_name)

layer_index = 6
seventh_layer = model.h[layer_index]

attention_weights = seventh_layer.attn.c_attn.weight
print("Attention Weights of the 7th Layer:")
print(attention_weights)

feed_forward_weights = seventh_layer.mlp.c_fc.weight
print("\nFeed-Forward Weights of the 7th Layer:")
print(feed_forward_weights)


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Attention Weights of the 7th Layer:
Parameter containing:
tensor([[ 0.1109, -0.0750,  0.0721,  ..., -0.0711, -0.0494, -0.1115],
        [-0.2255,  0.0296, -0.0349,  ...,  0.1043, -0.0363,  0.0626],
        [-0.0327, -0.1436,  0.0617,  ..., -0.0777,  0.0163,  0.0289],
        ...,
        [ 0.0309,  0.0490, -0.0798,  ..., -0.0406, -0.2152, -0.0557],
        [-0.1850,  0.0777,  0.1318,  ..., -0.1828,  0.0784, -0.0497],
        [ 0.1688,  0.0775,  0.0211,  ..., -0.0050, -0.0355,  0.1065]],
       requires_grad=True)

Feed-Forward Weights of the 7th Layer:
Parameter containing:
tensor([[-0.1218,  0.0713,  0.0619,  ..., -0.1984,  0.1075, -0.1217],
        [ 0.1185, -0.0547,  0.1252,  ..., -0.0299,  0.1321,  0.2523],
        [ 0.0006,  0.0529, -0.0573,  ...,  0.1458,  0.3539, -0.0049],
        ...,
        [ 0.1945, -0.0705,  0.0775,  ..., -0.2069, -0.1079,  0.0415],
        [-0.0502, -0.2534,  0.0429,  ...,  0.1170, -0.0706,  0.0645],
        [-0.0625, -0.1688, -0.1828,  ...,  0.0639, -0.07

In [5]:
with torch.no_grad():
    random_attention_weights = torch.randn(seventh_layer.attn.c_attn.weight.shape)
    seventh_layer.attn.c_attn.weight.copy_(random_attention_weights)

print("Randomized Attention Weights of the 7th Layer:")
print(seventh_layer.attn.c_attn.weight)

with torch.no_grad():
    random_feed_forward_weights = torch.randn(seventh_layer.mlp.c_fc.weight.shape)
    seventh_layer.mlp.c_fc.weight.copy_(random_feed_forward_weights)

print("\nRandomized Feed-Forward Weights of the 7th Layer:")
print(seventh_layer.mlp.c_fc.weight)

Randomized Attention Weights of the 7th Layer:
Parameter containing:
tensor([[ 0.5309,  0.7558,  0.0510,  ..., -0.3344, -0.0795, -1.1846],
        [ 1.0711, -0.1030, -0.3788,  ..., -0.7558, -0.0704,  1.1522],
        [ 0.1297, -1.3392,  0.1801,  ..., -0.7040,  1.4055,  0.7342],
        ...,
        [-0.9888,  0.1198, -0.2485,  ...,  0.7661, -0.1019,  0.1587],
        [ 0.1543, -0.0651, -0.3434,  ...,  0.7487,  1.6564,  0.7396],
        [-0.2632, -0.0202,  0.1859,  ..., -0.8714, -0.7482, -0.7151]],
       requires_grad=True)

Randomized Feed-Forward Weights of the 7th Layer:
Parameter containing:
tensor([[-0.6184, -0.4967, -0.4716,  ...,  1.6322, -0.1893, -1.3879],
        [ 0.2121,  0.1580, -2.2948,  ..., -0.7668,  1.1024,  1.1275],
        [-0.2457,  0.2759, -0.3181,  ...,  0.7713, -0.8398,  0.2837],
        ...,
        [ 1.4791,  1.1704, -0.9184,  ..., -0.4790,  1.1552,  0.0198],
        [-0.3647, -0.5796,  0.4559,  ...,  0.3094, -0.4878,  1.6286],
        [-0.4507, -0.2824,  0.3175